In [2]:
import pyranges as pr
import cerberus
import pandas as pd

## Some known transcripts aren't from a v29 / v41 source 10/21/22

In [6]:
h5 = 'gtex_cerberus.h5'
ca = cerberus.read(h5)

In [5]:
df = pd.read_csv('cerberus_transcript_novelty.tsv', sep='\t')

In [6]:
df.loc[df.transcript_id == 'ENSG00000160753[2,6,1]']

,original_transcript_id,ic,ic_id,tss_id,tss,tes_id,tes,gene_id,gene_name,original_transcript_name,transcript_triplet,transcript_id,transcript_name,tss_first_sd_issue,tes_last_sa_issue,source,ic_novelty,tss_novelty,tes_novelty
462643,ENST00000368347.8#4,6,ENSG00000160753_6,ENSG00000160753_2,2,ENSG00000160753_1,1.0,ENSG00000160753,RUSC1,RUSC1-202,"[2,6,1]","ENSG00000160753[2,6,1]","RUSC1[2,6,1]",False,False,lapa,Known,Known,Known
778395,ENST00000368347.8,6,ENSG00000160753_6,ENSG00000160753_2,2,ENSG00000160753_1,1.0,ENSG00000160753,RUSC1,ENST00000368347.8,"[2,6,1]","ENSG00000160753[2,6,1]","RUSC1[2,6,1]",False,False,gtex,Known,Known,Known

In [8]:
temp = df.loc[(df.ic_id=='ENSG00000160753_6')|(df.tss_id=='ENSG00000160753_2')|(df.tes_id=='ENSG00000160753_1')]
ref_sources = ['v29', 'v40']
temp = temp.loc[temp.source.isin(ref_sources)]
temp

,original_transcript_id,ic,ic_id,tss_id,tss,tes_id,tes,gene_id,gene_name,original_transcript_name,transcript_triplet,transcript_id,transcript_name,tss_first_sd_issue,tes_last_sa_issue,source,ic_novelty,tss_novelty,tes_novelty
180,ENST00000292254.8,3,ENSG00000160753_3,ENSG00000160753_2,2,ENSG00000160753_1,1.0,ENSG00000160753,RUSC1,RUSC1-201,"[2,3,1]","ENSG00000160753[2,3,1]","RUSC1[2,3,1]",False,False,v40,Known,Known,Known
1250,ENST00000368347.8,6,ENSG00000160753_6,ENSG00000160753_3,3,ENSG00000160753_1,1.0,ENSG00000160753,RUSC1,RUSC1-202,"[3,6,1]","ENSG00000160753[3,6,1]","RUSC1[3,6,1]",False,False,v40,Known,Known,Known
1251,ENST00000368349.8,2,ENSG00000160753_2,ENSG00000160753_2,2,ENSG00000160753_1,1.0,ENSG00000160753,RUSC1,RUSC1-203,"[2,2,1]","ENSG00000160753[2,2,1]","RUSC1[2,2,1]",False,False,v40,Known,Known,Known
1252,ENST00000368352.10,1,ENSG00000160753_1,ENSG00000160753_1,1,ENSG00000160753_1,1.0,ENSG00000160753,RUSC1,RUSC1-204,"[1,1,1]","ENSG00000160753[1,1,1]","RUSC1[1,1,1]",False,False,v40,Known,Known,Known
1253,ENST00000368354.7,5,ENSG00000160753_5,ENSG00000160753_1,1,ENSG00000160753_1,1.0,ENSG00000160753,RUSC1,RUSC1-205,"[1,5,1]","ENSG00000160753[1,5,1]","RUSC1[1,5,1]",False,False,v40,Known,Known,Known
4315,ENST00000462780.5,12,ENSG00000160753_12,ENSG00000160753_2,2,ENSG00000160753_2,2.0,ENSG00000160753,RUSC1,RUSC1-206,"[2,12,2]","ENSG00000160753[2,12,2]","RUSC1[2,12,2]",False,False,v40,Known,Known,Known
4703,ENST00000468764.5,14,ENSG00000160753_14,ENSG00000160753_2,2,ENSG00000160753_3,3.0,ENSG00000160753,RUSC1,RUSC1-208,"[2,14,3]","ENSG00000160753[2,14,3]","RUSC1[2,14,3]",False,False,v40,Known,Known,Known
4953,ENST00000471876.5,8,ENSG00000160753_8,ENSG00000160753_2,2,ENSG00000160753_1,1.0,ENSG00000160753,RUSC1,RUSC1-209,"[2,8,1]","ENSG00000160753[2,8,1]","RUSC1[2,8,1]",False,False,v40,Known,Known,Known
5516,ENST00000479924.5,13,ENSG00000160753_13,ENSG00000160753_2,2,ENSG00000160753_5,5.0,ENSG00000160753,RUSC1,RUSC1-211,"[2,13,5]","ENSG00000160753[2,13,5]","RUSC1[2,13,5]",False,False,v40,Known,Known,Known
6173,ENST00000490373.5,7,ENSG00000160753_7,ENSG00000160753_2,2,ENSG00000160753_2,2.0,ENSG00000160753,RUSC1,RUSC1-214,"[2,7,2]","ENSG00000160753[2,7,2]","RUSC1[2,7,2]",False,False,v40,Known,Known,Known
6310,ENST00000492536.5,15,ENSG00000160753_15,ENSG00000160753_2,2,ENSG00000160753_3,3.0,ENSG00000160753,RUSC1,RUSC1-215,"[2,15,3]","ENSG00000160753[2,15,3]","RUSC1[2,15,3]",False,False,v40,Known,Known,Known
6649,ENST00000497930.6,9,ENSG00000160753_9,ENSG00000160753_1,1,ENSG00000160753_1,1.0,ENSG00000160753,RUSC1,RUSC1-216,"[1,9,1]","ENSG00000160753[1,9,1]","RUSC1[1,9,1]",False,False,v40,Known,Known,Known
11311,ENST00000696599.1,4,ENSG00000160753_4,ENSG00000160753_1,1,ENSG00000160753_1,1.0,ENSG00000160753,RUSC1,RUSC1-217,"[1,4,1]","ENSG00000160753[1,4,1]","RUSC1[1,4,1]",False,False,v40,Known,Known,Known
246807,ENST00000292254.8,3,ENSG00000160753_3,ENSG00000160753_2,2,ENSG00000160753_1,1.0,ENSG00000160753,RUSC1,RUSC1-201,"[2,3,1]","ENSG00000160753[2,3,1]","RUSC1[2,3,1]",False,False,v29,Known,Known,Known
247912,ENST00000368347.8,6,ENSG00000160753_6,ENSG00000160753_3,3,ENSG00000160753_1,1.0,ENSG00000160753,RUSC1,RUSC1-202,"[3,6,1]","ENSG00000160753[3,6,1]","RUSC1[3,6,1]",False,False,v29,Known,Known,Known
247913,ENST00000368349.8,2,ENSG00000160753_2,ENSG00000160753_2,2,ENSG00000160753_1,1.0,ENSG00000160753,RUSC1,RUSC1-203,"[2,2,1]","ENSG00000160753[2,2,1]","RUSC1[2,2,1]",False,False,v29,Known,Known,Known
247914,ENST00000368352.9,1,ENSG00000160753_1,ENSG00000160753_1,1,ENSG00000160753_1,1.0,ENSG00000160753,RUSC1,RUSC1-204,"[1,1,1]","ENSG00000160753[1,1,1]","RUSC1[1,1,1]",False,False,v29,Known,Known,Known
247915,ENST00000368354.7,5,ENSG00000160753_5,ENSG00000160753_1,1,ENSG00000160753_1,1.0,ENSG00000160753,RUSC1,RUSC1-205,"[1,5,1]","ENSG00000160753[1,5,1]","RUSC1[1,5,1]",False,False,v29,Known,Known,Known
251011,ENST00000462780.5,12,ENSG00000160753_12,ENSG00000160753_2,2,ENSG00000160753_2,2.0,ENSG00000160753,RUSC1,RUSC1-206,"[2,12,2]","ENSG00000160753[2,12,2]","RUSC1[2,12,2]",False,False,v29,Known,Known,Known
251400,ENST00000468764.5,14,ENSG00000160753_14,ENSG00000160753_2,2,ENSG00000160753_3,3.0,ENSG00000160753,RUSC1,RUSC1-208,"[2,14,3]","ENSG00000160753[2,14,3]","RUSC1[2,14,3]",False,False,v29,Known,Known,Known
251650,ENST00000471876.5,8,ENSG00000160753_8,ENSG00000160753_2,2,ENSG00000160753_1,1.0,ENSG00000160753,RUSC1,RUSC1-209,"[2,8,1]","ENSG00000160753[2,8,1]","RUSC1[2,8,1]",False,False,v29,Known,Known,Known
252218,ENST00000479924.5,13,ENSG00000160753_13,ENSG00000160753_2,2,ENSG00000160753_5,5.0,ENSG00000160753,RUSC1,RUSC1-211,"[2,13,5]","ENSG00000160753[2,13,5]","RUSC1[2,13,5]",False,False,v29,Known,Known,Known
252877,ENST00000490373.5,7,ENSG00000160753_7,ENSG00000160753_2,2,ENSG00000160753_2,2.0,ENSG00000160753,RUSC1,RUSC1-214,"[2,7,2]","ENSG00000160753[2,7,2]","RUSC1[2,7,2]",False,False,v29,Known,Known,Known
253014,ENST00000492536.5,15,ENSG00000160753_15,ENSG00000160753_2,2,ENSG00000160753_3,3.0,ENSG00000160753,RUSC1,RUSC1-215,"[2,15,3]","ENSG00000160753[2,15,3]","RUSC1[2,15,3]",False,False,v29,Known,Known,Known

## Mapping file has more entries than unique cerberus IDs

Regarding the transcripts that are assigned to the same cerberus ID, these mostly look like they have the same original_transcript_id but differ in the suffix. (See first screenshot).
I looked at a pair of these transcripts with (ENST00000044462.11 and ENST00000044462.11-1) in the original GTF, and found that they differ only in the 3' UTR (See second screenshot).
These regions essentially were collapsed in the cerberus pipeline, which caused the transcripts with differing 3' UTRs in gtex to be consolidated in to one transcript from cerberus

In [28]:
f1 = 'gtex_to_cerberus_id.tsv'

df = pd.read_csv(f1, sep='\t')

In [30]:
print(len(df.index))
print(len(df.transcript_id.unique()))
print(len(df.original_transcript_id.unique()))

88696
88666
88696

In [31]:
df.loc[df.transcript_id.duplicated(keep=False)].sort_values(by='transcript_id')

,transcript_id,original_transcript_id
28637,"ENSG00000041357[1,1,2]",ENST00000044462.11-1
28636,"ENSG00000041357[1,1,2]",ENST00000044462.11
49250,"ENSG00000079156[1,11,2]",694903e4-a452-41de-a9ea-15c71909a3bc_ENSG00000...
49249,"ENSG00000079156[1,11,2]",694903e4-a452-41de-a9ea-15c71909a3bc-1_ENSG000...
44255,"ENSG00000083845[2,2,1]",ENST00000601521.5-1
44254,"ENSG00000083845[2,2,1]",ENST00000601521.5
65889,"ENSG00000085871[1,2,6]",ENST00000616265.4-1
65888,"ENSG00000085871[1,2,6]",ENST00000616265.4
56425,"ENSG00000101182[1,1,1]",ENST00000370873.8-1
56424,"ENSG00000101182[1,1,1]",ENST00000370873.8
82608,"ENSG00000104763[1,8,4]",ENST00000636435.1
82609,"ENSG00000104763[1,8,4]",ENST00000636435.1-1
70829,"ENSG00000113558[1,11,2]",ENST00000328392.10
70830,"ENSG00000113558[1,11,2]",ENST00000328392.10-1
53249,"ENSG00000115053[1,1,2]",ENST00000322723.8
53250,"ENSG00000115053[1,1,2]",ENST00000322723.8-1
7732,"ENSG00000116251[2,2,2]",ENST00000497965.5-1
7731,"ENSG00000116251[2,2,2]",ENST00000497965.5
52109,"ENSG00000119865[1,9,1]",38cab2e3-f7be-43a8-ad3d-6bd685755dc7-1_ENSG000...
52110,"ENSG00000119865[1,9,1]",38cab2e3-f7be-43a8-ad3d-6bd685755dc7_ENSG00000...
55158,"ENSG00000124228[1,8,1]",9c35a31c-b633-4fb1-bf27-c7eb7b977961_ENSG00000...
55157,"ENSG00000124228[1,8,1]",9c35a31c-b633-4fb1-bf27-c7eb7b977961-1_ENSG000...
68799,"ENSG00000134056[1,1,5]",ENST00000256441.4
68800,"ENSG00000134056[1,1,5]",ENST00000256441.4-1
23727,"ENSG00000134897[1,1,3]",ENST00000257336.5-1
23726,"ENSG00000134897[1,1,3]",ENST00000257336.5
10284,"ENSG00000138326[1,7,10]",ENST00000440692.5-1
10283,"ENSG00000138326[1,7,10]",ENST00000440692.5
81431,"ENSG00000147586[2,10,1]",09eff090-a04f-4960-8ab1-90f428736e8c-1_ENSG000...
81432,"ENSG00000147586[2,10,1]",09eff090-a04f-4960-8ab1-90f428736e8c_ENSG00000...
82437,"ENSG00000147586[2,6,1]",ENST00000519120.1
82438,"ENSG00000147586[2,6,1]",ENST00000519120.1-1
15203,"ENSG00000149196[1,20,1]",e83e2408-1f45-434b-854c-00590f9282ea-1_ENSG000...
15204,"ENSG00000149196[1,20,1]",e83e2408-1f45-434b-854c-00590f9282ea_ENSG00000...
82459,"ENSG00000154582[1,1,2]",ENST00000520242.5
82460,"ENSG00000154582[1,1,2]",ENST00000520242.5-1
82435,"ENSG00000154582[1,15,2]",ENST00000519082.5-1
82434,"ENSG00000154582[1,15,2]",ENST00000519082.5
82423,"ENSG00000154582[1,6,2]",ENST00000518127.5-1
82422,"ENSG00000154582[1,6,2]",ENST00000518127.5
81468,"ENSG00000154582[1,7,2]",11a0e2ea-f876-4f1b-bc3a-3a663251644e_ENSG00000...
81467,"ENSG00000154582[1,7,2]",11a0e2ea-f876-4f1b-bc3a-3a663251644e-1_ENSG000...
4305,"ENSG00000196890[1,1,5]",ed124237-136f-4bd5-81ba-199d210ed077
192,"ENSG00000196890[1,1,5]",0e715173-e3c3-4616-921e-ae193fdc93c7
59557,"ENSG00000198125[2,23,1]",c94c828f-e38a-42e3-b45d-b6d0a10cbf1b-1_ENSG000...
59558,"ENSG00000198125[2,23,1]",c94c828f-e38a-42e3-b45d-b6d0a10cbf1b_ENSG00000...
79260,"ENSG00000236753[1,11,5]",ENST00000454515.5-1
79259,"ENSG00000236753[1,11,5]",ENST00000454515.5
77967,"ENSG00000236753[1,17,5]",0c1778a0-7fda-43d7-a558-df28207e84dd_ENSG00000...
77966,"ENSG00000236753[1,17,5]",0c1778a0-7fda-43d7-a558-df28207e84dd-1_ENSG000...
79217,"ENSG00000236753[1,7,5]",ENST00000444245.5
79218,"ENSG00000236753[1,7,5]",ENST00000444245.5-1
79148,"ENSG00000236753[1,8,5]",ENST00000416220.5-1
79147,"ENSG00000236753[1,8,5]",ENST00000416220.5
75036,"ENSG00000272325[1,1,6]",ENST00000607016.1-1
75035,"ENSG00000272325[1,1,6]",ENST00000607016.1
71051,"ENSG00000273841[1,5,1]",ENST00000508954.3-1
71050,"ENSG00000273841[1,5,1]",ENST00000508954.3
81217,"ENSG00000280064[1,1,5]",db8b00b0-87a9-4fd4-a33d-550be7331c10
80262,"ENSG00000280064[1,1,5]",506d0114-3eb0-43fa-a43a-71d8aa9b42a1

In [ ]:
h5_annot = '../cerberus/cerberus_annot.h5'
ca = cerberus.read(h5_annot)

In [40]:
ca.tes_map.loc[(ca.tes_map.source == 'gtex')&(ca.tes_map.Chromosome=='chr15')&(ca.tes_map.Start <= 78548996)&(ca.tes_map.Name.str.contains('ENSG00000041357'))].sort_values(by='Start', ascending=False).head()

       Chromosome     Start       End Strand source               Name
786449      chr15  78548945  78549046      +   gtex  ENSG00000041357_2

In [41]:
ca.tes_map.loc[ca.tes_map.Name == 'ENSG00000041357_2']

       Chromosome     Start       End Strand       source               Name
778953      chr15  78548769  78549254      +          v40  ENSG00000041357_2
783815      chr15  78548769  78549254      +          v29  ENSG00000041357_2
785589      chr15  78548769  78549254      +         lapa  ENSG00000041357_2
786449      chr15  78548945  78549046      +         gtex  ENSG00000041357_2
786450      chr15  78549153  78549254      +         gtex  ENSG00000041357_2
787255      chr15  78548868  78548869      +          pas  ENSG00000041357_2
787256      chr15  78548907  78548930      +          pas  ENSG00000041357_2
787257      chr15  78549188  78549261      +          pas  ENSG00000041357_2
789942      chr15  78548791  78548792      +  polya_atlas  ENSG00000041357_2
789943      chr15  78548798  78548833      +  polya_atlas  ENSG00000041357_2
789944      chr15  78548851  78548879      +  polya_atlas  ENSG00000041357_2
789945      chr15  78549041  78549126      +  polya_atlas  ENSG00000041357_2
789946      chr15  78549126  78549160      +  polya_atlas  ENSG00000041357_2
789947      chr15  78549210  78549263      +  polya_atlas  ENSG00000041357_2

In [42]:
ca.tes.loc[ca.tes.Name == 'ENSG00000041357_2']

,Chromosome,Start,End,Strand,Name,source,novelty,gene_id,tes
164051,chr15,78548769,78549254,+,ENSG00000041357_2,"v40,v29,lapa,gtex,pas,polya_atlas",Known,ENSG00000041357,2

## Weird stuff going on w/ gtex stuff? 
* Yunzhe says that some transcripts from the transcript novelty file (which is output directly from the gtex gtf) don't match to the cerberus ids
* This is because all of the ones that are removed b/w the two files are from novel genes

In [2]:
def get_gtex_gene_nov(df):
    df['gene_novelty'] = 'Known'
    df.loc[df.gene_id.str.contains('chr'), 'gene_novelty'] = 'Novel'
    return df

def get_gtex_transcript_nov(df):
    df['transcript_novelty'] = 'Novel'
    df.loc[df.transcript_id.str.contains('ENST'), 'transcript_novelty'] = 'Known'
    return df

In [3]:
f1 = 'gtex_to_cerberus_id.tsv'
f2 = 'gtex_transcript_novelty.tsv'

df1 = pd.read_csv(f1, sep='\t')
df2 = pd.read_csv(f2, sep='\t')

In [5]:
df2.head()

,Unnamed: 0,transcript_id,transcript_novelty
0,0,dfe30c5c-ddd7-4ee8-a9ba-74556bd9dd87_chr10:628000,Novel
1,2,01252fde-2aa4-4b0d-99f6-c95a4efcc758_chr10:650000,Novel
2,4,5d705740-efaf-4cd9-9b68-71d6b775a3be_chr10:306...,Novel
3,6,115765b8-4233-49bb-a2bf-93683ac4e094_chr10:313...,Novel
4,8,6d54e9f3-0815-4ea6-a878-1ef2947c1cd0_chr10:482...,Novel

In [4]:
df1.head()

,transcript_id,original_transcript_id
0,"ENSG00000086015[5,22,1]",0016cd97-0137-4194-9821-910931c6e972_ENSG00000...
1,"ENSG00000162736[1,28,1]",001eea3f-368c-444f-96c0-539cb2204403_ENSG00000...
2,"ENSG00000084072[1,23,3]",0039fbf5-7334-40e1-a1a9-2aa34b6e009c_ENSG00000...
3,"ENSG00000137965[1,13,1]",003cbbd1-0cb2-43d0-ba48-daabd4d7d518_ENSG00000...
4,"ENSG00000127603[39,77,36]",004a6304-0523-477e-ad32-90215c977dca_ENSG00000...

In [10]:
df2.transcript_id.head().values

array(['dfe30c5c-ddd7-4ee8-a9ba-74556bd9dd87_chr10:628000',
       '01252fde-2aa4-4b0d-99f6-c95a4efcc758_chr10:650000',
       '5d705740-efaf-4cd9-9b68-71d6b775a3be_chr10:3069000',
       '115765b8-4233-49bb-a2bf-93683ac4e094_chr10:3132000',
       '6d54e9f3-0815-4ea6-a878-1ef2947c1cd0_chr10:4826000'], dtype=object)

In [23]:
# get list of transcripts that don't have a cerberus mapping
tids = list(set(df2.transcript_id.tolist())-set(df1.original_transcript_id.tolist()))
len(tids)

5022

In [24]:
gtf = 'flair_filter_transcripts.gtf'
df = pr.read_gtf(gtf, as_df=True)
df = get_gtex_gene_nov(df)
df = get_gtex_transcript_nov(df)

In [26]:
temp = df.loc[df.transcript_id.isin(tids)]
temp = temp[['transcript_id', 'gene_novelty']].drop_duplicates()
temp.groupby('gene_novelty').count()

              transcript_id
gene_novelty
Novel                  5022

## Get cerberus IDs for each transcript

In [5]:
ca = cerberus.read('gtex_cerberus.h5')

In [6]:
ca.t_map.source.unique()

array(['v40', 'v29', 'lapa', 'gtex'], dtype=object)

In [7]:
df = ca.t_map.loc[ca.t_map.source == 'gtex']

In [8]:
df.head()

,original_transcript_id,ic,ic_id,tss_id,tss,tes_id,tes,gene_id,gene_name,original_transcript_name,transcript_triplet,transcript_id,transcript_name,tss_first_sd_issue,tes_last_sa_issue,source
0,0016cd97-0137-4194-9821-910931c6e972_ENSG00000...,22,ENSG00000086015_22,ENSG00000086015_5,5,ENSG00000086015_1,1.0,ENSG00000086015,MAST2,0016cd97-0137-4194-9821-910931c6e972_ENSG00000...,"[5,22,1]","ENSG00000086015[5,22,1]","MAST2[5,22,1]",False,False,gtex
1,001eea3f-368c-444f-96c0-539cb2204403_ENSG00000...,28,ENSG00000162736_28,ENSG00000162736_1,1,ENSG00000162736_1,1.0,ENSG00000162736,NCSTN,001eea3f-368c-444f-96c0-539cb2204403_ENSG00000...,"[1,28,1]","ENSG00000162736[1,28,1]","NCSTN[1,28,1]",False,False,gtex
2,0039fbf5-7334-40e1-a1a9-2aa34b6e009c_ENSG00000...,23,ENSG00000084072_23,ENSG00000084072_1,1,ENSG00000084072_3,3.0,ENSG00000084072,PPIE,0039fbf5-7334-40e1-a1a9-2aa34b6e009c_ENSG00000...,"[1,23,3]","ENSG00000084072[1,23,3]","PPIE[1,23,3]",False,False,gtex
3,003cbbd1-0cb2-43d0-ba48-daabd4d7d518_ENSG00000...,13,ENSG00000137965_13,ENSG00000137965_1,1,ENSG00000137965_1,1.0,ENSG00000137965,IFI44,003cbbd1-0cb2-43d0-ba48-daabd4d7d518_ENSG00000...,"[1,13,1]","ENSG00000137965[1,13,1]","IFI44[1,13,1]",False,False,gtex
4,004a6304-0523-477e-ad32-90215c977dca_ENSG00000...,77,ENSG00000127603_77,ENSG00000127603_39,39,ENSG00000127603_36,36.0,ENSG00000127603,MACF1,004a6304-0523-477e-ad32-90215c977dca_ENSG00000...,"[39,77,36]","ENSG00000127603[39,77,36]","MACF1[39,77,36]",False,False,gtex

In [10]:
df[['transcript_id', 'original_transcript_id']].to_csv('gtex_to_cerberus_id.tsv', sep='\t', index=False)

## Get lists of known / novel genes / transcripts

In [19]:
gtf = 'flair_filter_transcripts.gtf'
df = pr.read_gtf(gtf, as_df=True)
df = get_gtex_gene_nov(df)
df = get_gtex_transcript_nov(df)

In [11]:
df = pr.read_gtf(gtf, as_df=True)
df = df[['gene_id']].drop_duplicates()
df['gene_novelty'] = 'Known'
df.loc[df.gene_id.str.contains('chr'), 'gene_novelty'] = 'Novel'
df.head()
df.to_csv('gtex_gene_novelty.tsv', sep='\t')

In [12]:
df = pr.read_gtf(gtf, as_df=True)
ts = df[['transcript_id']].drop_duplicates()
ts['transcript_novelty'] = 'Novel'
ts.loc[ts.transcript_id.str.contains('ENST'), 'transcript_novelty'] = 'Known'
ts.groupby('transcript_novelty').count()
ts.head()
# ts.to_csv('gtex_transcript_novelty.tsv', sep='\t')

## Get only known genes

In [32]:
df = pr.read_gtf('flair_filter_transcripts.gtf', as_df=True)

In [33]:
print(len(df.index))
df = df.loc[df.gene_id.str.contains('ENSG')]
print(len(df.index))

962547
951905

In [34]:
df.head()

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,gene_id,transcript_id,exon_number
12,chr10,FLAIR,transcript,5498696,5499570,.,-,.,ENSG00000178372.7,6168c158-18b2-4590-92f6-c1c968c4b3cb_ENSG00000...,NaN
13,chr10,FLAIR,exon,5498696,5499570,.,-,0,ENSG00000178372.7,6168c158-18b2-4590-92f6-c1c968c4b3cb_ENSG00000...,0
28,chr10,FLAIR,transcript,14877700,14878678,.,-,.,chr10:14873000_ENSG00000272853.1,c81d16e1-be22-46bf-b4a3-27d127f5c5b9,NaN
29,chr10,FLAIR,exon,14877700,14878678,.,-,0,chr10:14873000_ENSG00000272853.1,c81d16e1-be22-46bf-b4a3-27d127f5c5b9,0
34,chr10,FLAIR,transcript,22252065,22255955,.,+,.,chr10:22252000_ENSG00000279631.1,7be43b56-a050-448a-8d71-324d0c33b516,NaN

In [35]:
inds = df.loc[df.gene_id.str.contains('chr')].index.tolist()
df.loc[inds, 'gene_id'] = df.loc[inds, 'gene_id'].str.split('_', n=1, expand=True)[1]

In [36]:
df.head()

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,gene_id,transcript_id,exon_number
12,chr10,FLAIR,transcript,5498696,5499570,.,-,.,ENSG00000178372.7,6168c158-18b2-4590-92f6-c1c968c4b3cb_ENSG00000...,NaN
13,chr10,FLAIR,exon,5498696,5499570,.,-,0,ENSG00000178372.7,6168c158-18b2-4590-92f6-c1c968c4b3cb_ENSG00000...,0
28,chr10,FLAIR,transcript,14877700,14878678,.,-,.,ENSG00000272853.1,c81d16e1-be22-46bf-b4a3-27d127f5c5b9,NaN
29,chr10,FLAIR,exon,14877700,14878678,.,-,0,ENSG00000272853.1,c81d16e1-be22-46bf-b4a3-27d127f5c5b9,0
34,chr10,FLAIR,transcript,22252065,22255955,.,+,.,ENSG00000279631.1,7be43b56-a050-448a-8d71-324d0c33b516,NaN

In [31]:
len(df.loc[df.gene_id.str.contains('chr')].index)

770

In [28]:
len(df.loc[~df.transcript_id.str.contains('ENST')].index)

738165

In [26]:
df.loc[(df.gene_id.str.contains('chr'))&~(df.transcript_id.str.contains('ENST'))].head()

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,gene_id,transcript_id,exon_number
2,chr1,FLAIR,transcript,1232253,1235041,.,+,.,chr1:1232000_ENSG00000176022.4,a9ca82a1-c1d2-4d0a-bcff-672c3e94ba81,NaN
3,chr1,FLAIR,exon,1232253,1235041,.,+,0,chr1:1232000_ENSG00000176022.4,a9ca82a1-c1d2-4d0a-bcff-672c3e94ba81,0
4,chr1,FLAIR,transcript,6393509,6394391,.,+,.,chr1:6393000_ENSG00000271746.1,a1359d21-b10f-4022-8db8-9bc0e9407d12,NaN
5,chr1,FLAIR,exon,6393509,6394391,.,+,0,chr1:6393000_ENSG00000271746.1,a1359d21-b10f-4022-8db8-9bc0e9407d12,0
10,chr1,FLAIR,transcript,23080845,23084727,.,+,.,chr1:23080000_ENSG00000004487.15,13906ae4-0e7e-4e90-88b8-c8fe4b07f94c,NaN

In [23]:
df = pr.PyRanges(df)

In [ ]:
## oTher stuff

In [18]:
df = pr.read_gtf('flair_filter_transcripts.gtf')

In [19]:
df = df.as_df()

In [20]:
df.head()

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,gene_id,transcript_id,exon_number
0,chr1,FLAIR,transcript,785781,787672,.,+,.,ENSG00000237491.8,c0e70edb-ee9e-4863-b844-af03092e0afe,NaN
1,chr1,FLAIR,exon,785781,787672,.,+,1862,ENSG00000237491.8,c0e70edb-ee9e-4863-b844-af03092e0afe,0
2,chr1,FLAIR,transcript,1013422,1014541,.,+,.,chr1:1013000,f940fb0a-3c9b-4989-b060-7adc659c4467_chr1:1013000,NaN
3,chr1,FLAIR,exon,1013422,1014541,.,+,0,chr1:1013000,f940fb0a-3c9b-4989-b060-7adc659c4467_chr1:1013000,0
4,chr1,FLAIR,transcript,1232253,1235041,.,+,.,chr1:1232000_ENSG00000176022.4,a9ca82a1-c1d2-4d0a-bcff-672c3e94ba81,NaN

In [11]:
genes = df[['gene_id']].drop_duplicates()
genes['gene_novelty'] = 'Novel'
genes.loc[genes.gene_id.str.contains('ENSG'), 'gene_novelty'] = 'Known'
genes.groupby('gene_novelty').count()

              gene_id
gene_novelty
Known           16274
Novel            4793

In [15]:
ts = df[['transcript_id']].drop_duplicates()
ts['transcript_novelty'] = 'Novel'
ts.loc[ts.transcript_id.str.contains('ENST'), 'transcript_novelty'] = 'Known'
ts.groupby('transcript_novelty').count()

                    transcript_id
transcript_novelty
Known                       21393
Novel                       72325

In [16]:
ts.loc[ts.transcript_novelty == 'Novel']

                                            transcript_id transcript_novelty
0                    c0e70edb-ee9e-4863-b844-af03092e0afe              Novel
2       f940fb0a-3c9b-4989-b060-7adc659c4467_chr1:1013000              Novel
4                    a9ca82a1-c1d2-4d0a-bcff-672c3e94ba81              Novel
6       ffcf6444-2d57-4390-a915-c658140698f5_chr1:1318000              Novel
8                    8cd8c06a-ed11-405f-9955-efe2ea3df6bf              Novel
...                                                   ...                ...
962433  6c0c928d-51d1-4083-9382-37fdd1dc7124_ENSG00000...              Novel
962460  022b0ce1-a05a-43f4-a43b-64b84d7c5b49_ENSG00000...              Novel
962466  ec1fae0e-8321-49b9-846b-ac185a689b42_ENSG00000...              Novel
962472  924b8dec-fc8b-49be-a5c9-299e8e31443e_ENSG00000...              Novel
962521               02eb4919-694b-4bf3-96db-621db54048c6              Novel

[72325 rows x 2 columns]