In [1]:
import pandas as pd
import numpy as np
import scipy.stats as st
import seaborn as sns
import sys
import os

p = os.path.dirname(os.path.dirname(os.getcwd()))
sys.path.append(p)

from scripts.utils import *
from scripts.plotting import *

In [2]:
df = pd.read_csv('../../lr_bulk/talon/human_talon_abundance.tsv', sep='\t')
tpm_df = get_tpm_table(df, sample='cell_line', how='gene', save=True)

39285

In [6]:
temp = df[['annot_gene_id', 'annot_gene_name']].drop_duplicates()
tpm_df = tpm_df.merge(temp, how='left', 
                      left_index=True, right_on='annot_gene_id')
tpm_df.set_index('annot_gene_name', inplace=True)
tpm_df.drop('annot_gene_id', axis=1, inplace=True)

In [11]:
top_genes = pd.DataFrame()
for c in tpm_df.columns:
    tpm_df = tpm_df.sort_values(by=c, ascending=False)
#     print(df.head())
    temp = pd.DataFrame(tpm_df.iloc[:10, :].copy(deep=True).index.to_list(), 
                        columns=[c])
    top_genes = pd.concat([top_genes, temp], axis=1)

In [12]:
top_genes.head()

,gm12878_1_1,gm12878_1_2,gm12878_1_3,gm12878_1_4,gm12878_3_1,gm12878_2_1,gm12878_2_2,pgp1_1_1,pgp1_1_2,h9_1_1,...,pgp1_excite_neuron_1_1,pgp1_excite_neuron_1_2,h9_neural_crest_1_1,h9_neural_crest_1_2,h9_osteocyte_1_1,h9_osteocyte_1_2,h9_panc_progen_1_1,h9_panc_progen_1_2,h9_panc_beta_1_1,h9_panc_beta_1_2
0,ACTB,ACTB,TMSB4X,TMSB4X,ACTB,HSPA8,HSPA8,EEF1A1,RPS2,EEF1A1,...,TUBA1A,TUBA1A,EEF1A1,EEF1A1,EEF1A1,EEF1A1,EEF1A1,EEF1A1,EEF1A1,ANXA1
1,TMSB4X,TMSB4X,ACTB,ACTB,TMSB4X,TMSB4X,TMSB4X,RPS2,EEF1A1,GAPDH,...,CKB,CKB,TUBA1A,TUBA1A,ANXA2,ANXA2,HSPA8,HSPA8,GCG,EEF1A1
2,EEF1A1,EEF1A1,GAPDH,GAPDH,ACTG1,TUBA1B,TUBA1B,GAPDH,GAPDH,ENO1,...,TUBB3,TUBB3,HSPA8,HSPA8,HSPA8,HSPA8,EEF1G,DLK1,EEF1G,GCG
3,GAPDH,GAPDH,B2M,RPL3,ENO1,ENO1,B2M,ENO1,EEF1G,HSPA8,...,EEF1A1,EEF1A1,HNRNPA1,HNRNPA1,FSTL1,COL1A2,HNRNPA1,EEF1G,HNRNPA1,EEF1G
4,CD74,RPL3,MT-CO2,CD74,IGHM,EEF1A1,ENO1,EEF1G,ENO1,ACTB,...,MALAT1,NEFM,ENO1,EEF1G,COL1A2,FSTL1,TUBA1A,HNRNPA1,RPL3,RPL3

In [14]:
top_genes.to_csv('cell_line_top_10_genes.tsv', sep='\t')